import { action, card, head, input, select, switcher } from './primitives.js';
export function gettingStarted() {
  const steps = [['Completa el perfil de tu organización','#page=organization','Abrir'],['Invita a tu equipo','','Invitar'],['Revisa aseguradoras','#page=insurers','Abrir'],['Conecta WhatsApp en tu teléfono','#page=integrations','Abrir'],['Envía tu primer mensaje','#page=engage','Abrir']];
  const row = ([label, href, text]) => `<div class="st-check-row"><span class="st-check">✓</span><span>${label}</span>${href ? `<a href="${href}">${text}</a>` : action(text)}</div>`;
  return `<div class="st-narrow">${head('Primeros pasos','Completa estos pasos para dejar tu ubicación lista.')}<p>3 de 5 completados</p><progress max="5" value="3"></progress>${card(`<h3>Obligatorias</h3>${steps.map(row).join('')}`)}${card(`<h3>Opcionales</h3>${row(['Revisa tus precios','#page=prices','Abrir'])}${row(['Configura tus facturas','#page=fiscal','Abrir'])}`)}${card(`<h2>Configuración de cuenta programada por Avance</h2><p>Avance completa estos pasos de configuración de tu cuenta.</p>${['Configuración del sector','Conexión de WhatsApp Business','Configuración del perfil del asistente de IA','Plantillas de mensajes de WhatsApp','Capacitación del equipo','Lanzamiento del sitio web'].map(x => `<div class="st-check-row"><span class="st-check">✓</span>${x}</div>`).join('')}`)}</div>`;
}
export function profile() {
  return `<div class="st-profile-grid"><div>${head('Mi perfil','Actualiza tus datos personales y foto de perfil.')}${card(`<div class="st-avatar">DD</div><b>Foto de Perfil</b><p>Haz clic en el icono de la cámara para subir una nueva foto</p><div class="st-grid">${input('Nombre','Dental')}${input('Apellido','Demo')}${input('Correo Electrónico','dental-demo@avance.test')}${input('Número de Teléfono')}${select('Zona Horaria','America/Denver')}</div><p>Detectada: America/Denver</p><h3>Contacto de Emergencia</h3><div class="st-grid">${input('Nombre')}${input('Relación')}${input('Teléfono')}${input('Correo electrónico')}</div><div class="st-right">${action('Guardar Cambios',true)}</div>`)}</div><div>${card(`<h2>Preferencias de comunicación</h2><p>Elige si AvanceAI LLC puede enviarte mensajes de texto de marketing.</p>${switcher('Mensajes de texto de marketing de AvanceAI LLC')}${input('Número de teléfono para textos de marketing')}<p class="st-small">Acepto recibir mensajes de texto promocionales automatizados y recurrentes de AvanceAI LLC sobre productos, eventos y ofertas al número proporcionado. La frecuencia de los mensajes varía. Pueden aplicarse tarifas de mensajes y datos. Responde STOP para cancelar o HELP para obtener ayuda. El consentimiento no es condición de compra. Consulte nuestros <a href="https://avance.ai/terms">Términos</a> y <a href="https://avance.ai/privacy">Política de Privacidad</a>.</p>`)}</div>${card(`<h2>Cambiar Contraseña</h2><p>Actualiza la contraseña de tu cuenta.</p>${input('Contraseña Actual','','password')}${input('Nueva Contraseña','','password')}${input('Confirmar Nueva Contraseña','','password')}${action('Actualizar Contraseña',true)}`)}</div>`;
}
export function organization() {
  return `<div class="st-narrow">${head('Organización','Gestiona la información de tu organización y la configuración de la zona horaria.')}${card(`<div class="st-grid">${input('Nombre de la organización *','Dental Implant Clinic Demo')}${select('Zona Horaria *','Nueva York (Hora del Este)')}${select('Idioma Predeterminado','Español')}</div><p>Este será el idioma predeterminado para tu cuenta</p><div class="st-logo-box"><div><b>Sube tu logotipo</b><p>Haz que tu marca esté presente en todo el espacio de trabajo.</p><p>Usa un PNG, JPG, SVG o WebP horizontal con mínimo 128 px de ancho y 37 px de alto, máximo 4096 px por lado (relación 1:1 a 3.5:1).</p></div><div class="st-logo">ap</div><div><b>Current Logo</b><p>0x0px • 0.0 KB</p><span>Logotipo asignado</span></div></div><div class="st-right">${action('Quitar')}${action('Subir archivo')}${action('Guardar',true)}</div>`)}</div>`;
}
export function tags() {
  return `<div class="st-narrow">${head('Etiquetas','Gestiona las etiquetas permitidas para clientes potenciales y contactos')}${card(`<div class="st-row st-between"><h3>Grupos de etiquetas</h3>${action('Agregar grupo',true)}</div><div class="st-tag-layout"><div class="st-tag-selected">Pagador <span>2</span></div><div><div class="st-row st-between"><div><h3>Etiquetas en Pagador</h3><p>Pagador · pagador · seleccionar como máximo 1 · 2 etiqueta(s)</p></div>${action('Agregar etiqueta',true)}</div>${[['aseguradora-eps','Insurer / EPS','Aseguradora/EPS','The patient is covered by an insurer or EPS.','El paciente se atiende por aseguradora o EPS.'],['particular','Self-pay','Particular','The patient is self-pay.','El paciente paga de forma particular.']].map(([slug,en,es,descEn,descEs]) => `<div class="st-card"><b>${slug}</b><p>EN: ${en}<br>ES: ${es}<br>Desc EN: ${descEn}<br>Desc ES: ${descEs}</p>${action('Editar')}${action('Eliminar')}</div>`).join('')}</div></div>`)}</div>`;
}
export function taskTemplates(tab) {
  return `<div class="st-narrow">${head('Plantillas de tareas','Administra las tareas guardadas desde las que el equipo puede empezar.')}<nav class="st-tabs">${[['Contact','Plantillas de contacto'],['User','Plantillas de usuario']].map(([key,label]) => `<a href="#page=task-templates&tab=${key}" class="${tab===key?'active':''}">${label}</a>`).join('')}</nav>${card(`<div class="st-row st-between"><h3>Categorías</h3>${action('Nueva categoría',true)}</div><p class="st-empty">Aún no hay categorías.</p>`)}${card(`<div class="st-row st-between"><h3>Plantillas</h3>${action('Nueva plantilla',true)}</div><p class="st-empty">Aún no hay plantillas.</p>`)}</div>`;
}
