import { groups, priceProducts } from '../../data/settings/fixtures.js';
import { action, card, head, select, tabs } from './primitives.js';
export function fiscal() {
  return `<div class="st-narrow"><div class="st-error" role="alert">No se pudo cargar la facturación electrónica ${action('Reintentar')}</div><div class="st-card st-center">Próximamente</div><div class="st-error" role="alert">No se pudo cargar la evaluación del proveedor. ${action('Reintentar')}</div></div>`;
}
export function prices(tab) {
  const nav = tabs('prices',[['Products','Productos'],['Rules','Reglas de Precios'],['Groups','Grupos'],['Promos','Promos']],tab);
  let body = '';
  if (tab === 'Products') body = `<div class="st-row st-filters"><input placeholder="Buscar productos..." aria-label="Buscar productos" readonly>${select('Categorías','Todas las Categorías')}${select('Estados','Todos los Estados')}${action('Rango de precio: Precio Base / Cualquiera')}${action('Título Alternativo')}</div><div class="st-row">0 Con seleccionados: ${action('Archivar')}</div><div class="st-table-scroll"><table class="st-table"><thead><tr>${['□','Destacado','Producto','Precio Base','Precio Actual','Estado','Acciones'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${priceProducts.map(([code,price,state])=>`<tr><td>□</td><td>☆</td><td><b>Producto sin título</b><small>${code}</small></td><td>${price}</td><td>${price}</td><td><span class="st-pill">${state}</span></td><td>${action('Editar')} ${action('Acciones')}</td></tr>`).join('')}</tbody></table></div>`;
  if (tab === 'Rules') body = `<div class="st-note">Crea descuentos y promociones para tus productos.</div><div class="st-row st-between"><h3>Reglas de Precios</h3>${action('Nueva Regla',true)}</div><div class="st-empty">No hay reglas de precios todavía. Crea una para ofrecer descuentos y promociones.</div>`;
  if (tab === 'Groups') body = `<div class="st-note">Agrupa productos para el catalogo publico. Los grupos publicos pueden aparecer aunque no tengan productos.</div><div class="st-row st-between"><h3>Grupos de productos</h3>${action('Crear grupo',true)}</div>${groups.map(([name,slug],i)=>`<div class="st-group-row"><div><b>${name}</b><p>Orden ${i<9?(i+1)*10:900+i-9} · ${slug}</p><span class="st-pill">${i<9?'Publico':'Privado'}</span></div><div>${action('Editar')} ${action('Eliminar')}</div></div>`).join('')}`;
  if (tab === 'Promos') body = `<div class="st-row st-between"><div><h3>Promos</h3><p>Administra códigos promo de posesión para esta ubicación. Los códigos se normalizan y se bloquean tras la primera activación.</p></div>${action('Nueva promo',true)}</div><div class="st-note">Los códigos archivados solo se pueden reutilizar creando un nuevo UUID de Promo; editar el historial nunca reabre un código bloqueado.</div><div class="st-row"><input placeholder="Buscar por código..." readonly>${select('Estado','Todas')}</div><div class="st-error" role="alert">No se pudieron cargar las promos.</div>`;
  return `<div class="st-wide">${head('Precios','Administra tus servicios, precios y costos asociados (no se cobran).',action('Nuevo Producto',true))}${nav}<div class="st-price-body">${body}</div></div>`;
}
