import { button, table } from "../../ui.js";
import { patientId } from "../../fixture.js";
import { toothChart } from "../tooth-chart.js";
const keys = ["Enter", "Progress notes", "Tooth initials"];
const labels = ["Registrar", "Evolución de procedimientos", "Estado inicial"];
const catalogue = ["230101 · EXODONCIA DE DIENTE PERMANENTE UNIRRADICULAR", "230102 · EXODONCIA DE DIENTE PERMANENTE MULTIRRADICULAR", "230103 · EXODONCIA DE DIENTES PERMANENTES", "230201 · EXODONCIA DE DIENTE TEMPORAL UNIRRADICULAR", "230202 · EXODONCIA DE DIENTE TEMPORAL MULTIRRADICULAR", "230203 · EXODONCIA DE DIENTES TEMPORALES", "231101 · EXODONCIA QUIRURGICA UNIRRADICULAR", "231201 · EXODONCIA QUIRURGICA MULTIRRADICULAR", "231301 · EXODONCIA DE INCLUIDO EN POSICION ECTOPICA CON ABO", "231302 · EXODONCIA DE INCLUIDO EN POSICION ECTOPICA CON ABO", "231303 · EXODONCIA DE DIENTE INCLUIDO", "231401 · EXODONCIAS MULTIPLES CON ALVEOLOPLASTIA, POR CUADR", "231501 · COLGAJO DESPLAZADO PARA ABORDAJE DE DIENTE RETENID", "232101 · OBTURACION DENTAL CON AMALGAMA", "232102 · Resina de 1 superficie · 290.000 COP", "232103 · OBTURACION DENTAL CON IONOMERO DE VIDRIO", "232104 · OBTURACION DENTAL", "232201 · OBTURACION TEMPORAL POR DIENTE", "232301 · COLOCACION DE PIN MILIMETRICO", "232401 · RECONSTRUCCION DE ANGULO INCISAL CON RESINA DE FOT"];
const enter = () => `<div class="chart-entry"><label>Código de procedimiento<input placeholder="Buscar por código o nombre"></label><div class="catalogue">${catalogue.map((x) => `<button type="button" data-inert>${x}</button>`).join("")}</div><label>Estado<select><option>Planificado</option></select></label><div><b>Diente</b><p>Seleccione un diente en el odontograma</p></div><div><b>Superficies</b><div class="surface-buttons">${["M", "O", "I", "D", "B", "F", "L", "V"].map((x) => `<button class="btn" disabled>${x}</button>`).join("")}</div></div><label>Profesional<select><option></option></select></label><label>Fecha<input type="date" value="2026-09-19"></label><label>Cantidad<input type="number" value="1"></label><div><b>Precio</b><p>Ninguno</p></div><label>Prioridad<select><option>Ninguno</option></select></label><label>Pronóstico<select><option>Ninguno</option></select></label>${button("Agregar al odontograma", true)}</div>`;
const progress = () => table(["Fecha", "Diente", "Sup.", "Procedimiento", "Estado", "Profesional", "Precio", ""], [
  ["2026-09-03", "", "", "CONSULTA DE PRIMERA VEZ POR ODONTOLOGIA GENERAL", "Realizado", "Natalia Vélez", "", `<select aria-label="Cambiar estado"><option>Cambiar estado</option></select>${button("Notas")}${button("Facturar")}${button("Eliminar")}`],
  ["2026-09-03", "16", "O", "OBTURACION DENTAL CON RESINA DE FOTOCURADO", "Realizado", "Natalia Vélez", "", `<select aria-label="Cambiar estado"><option>Cambiar estado</option></select>${button("Notas")}${button("Facturar")}${button("Eliminar")}`],
  ["2026-08-20", "16", "O", "Caries", "Condición", "Natalia Vélez", "", `<select aria-label="Cambiar estado"><option>Cambiar estado</option></select>${button("Notas")}${button("Eliminar")}`],
]);
const initial = () => `<p>Sin estados iniciales.</p><div><b>Diente</b><p>Seleccione un diente en el odontograma</p></div><label>Tipo<select><option>Ausente</option></select></label><button class="btn primary" disabled>Agregar</button>`;
const denseTabs = (sub) => `<nav class="tabs subtabs" aria-label="Odontograma">${keys.map((key, i) => `<a class="${sub === key ? "active" : ""}" href="#page=patients&patient=${patientId}&tab=Dental%20chart&sub=${encodeURIComponent(key)}">${labels[i]}</a>`).join("")}</nav>`;
const denseEnter = () => `<div class="chart-entry dense-chart-entry"><div class="dense-chart-code"><label>Código de procedimiento<input placeholder="Buscar por código o nombre"></label><div class="catalogue">${catalogue.map((x) => `<button type="button" data-inert>${x}</button>`).join("")}</div></div><div class="dense-chart-tooth"><div><b>Diente</b><p>Seleccione un diente en el odontograma</p></div><div><b>Superficies</b><div class="surface-buttons">${["M", "O", "I", "D", "B", "F", "L", "V"].map((x) => `<button class="btn" disabled>${x}</button>`).join("")}</div></div></div><div class="dense-chart-fields"><label>Estado<select><option>Planificado</option></select></label><label>Profesional<select><option></option></select></label><label>Fecha<input type="date" value="2026-09-19"></label><label>Cantidad<input type="number" value="1"></label><div><b>Precio</b><p>Ninguno</p></div><label>Prioridad<select><option>Ninguno</option></select></label><label>Pronóstico<select><option>Ninguno</option></select></label></div>${button("Agregar al odontograma", true)}</div>`;
export function chartPanel(sub, variant) {
  if (variant === "dense") return `<div class="chart-filter"><div class="row">${button("Ajustes")}${button("Exportar")}${button("Estados")}<select aria-label="Profesionales"><option>Todos los profesionales</option></select><label>A la fecha<input type="date"></label><label><input type="checkbox"> Mostrar eliminados</label></div></div>${denseTabs(sub)}<div class="chart-workspace dense-chart-workspace"><div class="dense-chart-anatomy">${toothChart()}</div>${sub === "Progress notes" ? "" : `<aside class="chart-rail">${sub === "Tooth initials" ? initial() : denseEnter()}</aside>`}</div>${sub === "Progress notes" ? `<div class="dense-chart-progress">${progress()}</div>` : ""}`;
  return `<div class="chart-filter"><span>Ana García <span class="muted">Odontograma</span></span><div class="row">${button("Ajustes")}${button("Exportar")}${button("Estados")}<select aria-label="Profesionales"><option>Todos los profesionales</option></select><label>A la fecha<input type="date"></label><label><input type="checkbox"> Mostrar eliminados</label></div></div><div class="chart-workspace"><div>${toothChart()}</div><aside class="chart-rail"><nav class="tabs subtabs" aria-label="Odontograma">${keys.map((key, i) => `<a class="${sub === key ? "active" : ""}" href="#page=patients&patient=${patientId}&tab=Dental%20chart&sub=${encodeURIComponent(key)}">${labels[i]}</a>`).join("")}</nav>${sub === "Progress notes" ? progress() : sub === "Tooth initials" ? initial() : enter()}</aside></div>`;
}
