import { asset } from "../fixture.js";
const upper = [18, 17, 16, 15, 14, 13, 12, 11, 21, 22, 23, 24, 25, 26, 27, 28];
const lower = [48, 47, 46, 45, 44, 43, 42, 41, 31, 32, 33, 34, 35, 36, 37, 38];
const toothType = (n) => [18, 17, 16, 27, 28, 48, 47, 46, 37, 38].includes(n) ? "16" : [15, 14, 24, 25, 45, 44, 34, 35].includes(n) ? "14" : [13, 12, 23, 22, 43, 42, 33, 32].includes(n) ? "13" : "11";
const occlusalType = (n) => [18, 17, 16, 26, 27, 28, 48, 47, 46, 36, 37, 38].includes(n) ? "16" : "14";
const toothAsset = (n, view) => view === "occlusal" ? `../shared/data/patient/assets/${occlusalType(n)}_occl-healthy.svg` : asset(`${toothType(n)}-healthy.svg`);
const row = (nums, view, arch) => `<div class="toothrow ${view} ${arch}">${nums.map((n) => {
  const placeholder = view === "occlusal" && [13, 12, 11, 21, 22, 23, 43, 42, 41, 31, 32, 33].includes(n);
  const mirror = [21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38].includes(n);
  return `<div class="tooth${n === 16 ? " restored" : ""}">${view === "side" && arch === "upper" || view === "side" && arch === "lower" ? `<span>${n}</span>` : ""}<div class="tooth-image${placeholder ? " placeholder" : ""}">${placeholder ? "" : `<img class="${mirror ? "mirror" : ""}" src="${toothAsset(n, view)}" alt="Diente ${n}">`}</div></div>`;
}).join("")}</div>`;
export function toothChart() {
  return `<section class="toothchart"><div class="tooth-heading"><div><b>Carta dental</b><p>Haz clic en un diente. Para selección múltiple, usa CMD/CTRL + clic.</p></div><div class="tooth-controls">${[["Vista oclusal", "icon_occl"], ["Muelas del juicio", "icon_8"], ["Hueso", "icon_gum"], ["Pulpa", "icon_pulp"], ["Borrar selección", "icon_no_selection"]].map(([label, icon]) => `<button class="btn" type="button" aria-label="${label}" data-inert><img src="../shared/data/patient/assets/${icon}.svg" alt=""></button>`).join("")}</div></div>${row(upper, "side", "upper")}${row(upper, "occlusal", "upper")}${row(lower, "occlusal", "lower")}${row(lower, "side", "lower")}<div class="dental-report"><h3>Información dental</h3><p>El odontograma muestra 32 dientes permanentes y faltan 0 dientes.</p><table><thead><tr><th></th><th>Dientes permanentes</th></tr></thead><tbody><tr><th>Maxilar superior</th><td>${upper.join(", ")}</td></tr><tr><th>Maxilar inferior</th><td>${lower.join(", ")}</td></tr></tbody></table><p>Azul en negrita: el diente tiene un tratamiento o hallazgo. Rojo en negrita cursiva: el diente presenta un problema (caries, inflamación, diagnóstico, desgaste o decoloración).</p>${[["Caries", "No hay dientes con caries."], ["Obturaciones", "16 (O)"], ["Tratamientos de conducto", "No hay dientes endodonciados."], ["Diagnósticos", "sin diagnóstico registrado"], ["Desgaste", "sin desgaste registrado"], ["Decoloración", "sin decoloración registrada"], ["Ortodoncia", "sin hallazgo ortodóncico registrado"], ["Prótesis", "No hay prótesis."], ["Estado periodontal", "el periodonto está sano"]].map(([k, v]) => `<p><b>${k}:</b> ${v}</p>`).join("")}</div></section>`;
}
